# Generated by Django 5.1.4 on 2024-12-24 21:53

import apps.features.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.features.models.feature_directory_path)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
