# Generated by Django 5.1.4 on 2024-12-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='designation',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
