# Generated by Django 5.1.4 on 2024-12-24 21:53

import apps.car.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.IntegerField(choices=[(1, 'Toyota'), (2, 'Renault'), (3, 'Volkswagen'), (4, 'Citroen')])),
                ('model', models.CharField(max_length=40)),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1990)])),
                ('type', models.IntegerField(choices=[(1, 'Auto'), (2, 'Pickup'), (3, 'Comercial'), (4, 'Suv'), (5, 'Crossover')], default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.car.models.car_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_car.car')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_features.feature')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(through='apps_car.CarFeature', to='apps_features.feature'),
        ),
    ]
