# Generated by Django 5.1.4 on 2025-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_car', '0002_alter_car_features'),
        ('apps_features', '0003_alter_feature_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(through='apps_car.CarFeature', to='apps_features.feature'),
        ),
    ]
